deploymentName: users-deployment
deploymentLabel: users


replicaCount : 1

image:
   repository: pledika/users
   tag: latest
containerPort: 8082

service:
  type: LoadBalancer
  port: 8082
  targetPort: 8080

config_enabled: true 
zipkin_enabled: true 
profile_enabled: true 
eureka_enabled: false 