deploymentName: zipkin-deployment
deploymentLabel: zipkin


replicaCount : 1

image:
   repository: openzipkin/zipkin
   tag: latest
containerPort: 9411

service:
  type: LoadBalancer
  port: 9411
  targetPort: 9411 

config_enabled: true 
zipkin_enabled: false 
profile_enabled: true 
eureka_enabled: true 