deploymentName: loans-deployment
deploymentLabel: loans


replicaCount : 1

image:
   repository: pledika/loans
   tag: latest
containerPort: 8081

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

config_enabled: true 
zipkin_enabled: true 
profile_enabled: true 
eureka_enabled: true