apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: gatewayserver
  template:
   metadata:
     labels:
       app: gatewayserver
   spec:
     containers:
     - name: gatewayserver
       image: pledika/gatewayserver:latest
       ports:
        - containerPort: 8072
       env:
       - name: SPRING_PROFILES_ACTIVE
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap
             key: SPRING_PROFILES_ACTIVE
             
       - name: SPRING_CONFIG_IMPORT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap
             key: SPRING_CONFIG_IMPORT       
                  
       - name: OTEL_TRACES_EXPORTER
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap
             key: OTEL_TRACES_EXPORTER
             
       - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap
             key: OTEL_EXPORTER_ZIPKIN_ENDPOINT
             
       - name: OTEL_PROPAGATORS
         valueFrom: 
            configMapKeyRef:
              name: monkata-configmap
              key: OTEL_PROPAGATORS 
              
       - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
         valueFrom: 
            configMapKeyRef:
              name: monkata-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE                             
---       
apiVersion: v1
kind: Service 
metadata: 
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072            